name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana-backend:
    name: Qodana (Backend)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 'Qodana Scan — Backend (Python)'
        uses: JetBrains/qodana-action@v2025.3
        with:
          args: --config,qodana-backend.yaml
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_BACKEND }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

  qodana-frontend:
    name: Qodana (Frontend)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 'Qodana Scan — Frontend (JS/TS)'
        uses: JetBrains/qodana-action@v2025.3
        with:
          args: --config,qodana-frontend.yaml
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_FRONTEND }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
